### ISSUE TITLE
Error: When im trying with blue boyfriend at winter holiday he let me out (fnf Minus)

### ISSUE THREAD

**Issue by B-Si** [ninjamuffin99/Funkin#1092]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

**Comment by PurpleButNotALight** [comment]
just stop

**Comment by Windows1Door2Daniel** [comment]
say that to the mod creator

this is for the vanila game

**Comment by B-Si** [comment]
@PurpleButNotALight Stop Bringing Broker of Issues (ninjamuffin99)

**Comment by PurpleButNotALight** [comment]
> @PurpleButNotALight Stop Bringing Broker of Issues (ninjamuffin99)

bro you just bloat the issue tracker with these stupid questions

**Comment by Windows1Door2Daniel** [comment]
hey look

Mufin ninja 99
