### ISSUE TITLE
![Uploading iconGrid.png…]()

### ISSUE THREAD

**Issue by B-Si** [ninjamuffin99/Funkin#1093]
![B-Sides icongrid…]()

_Originally posted by @B-Si in https://github.com/ninjamuffin99/Funkin/issues/1090#issuecomment-841229829_

**Comment by B-Si** [comment]
![iconGrid](https://user-images.githubusercontent.com/84184839/118275079-9e7a2600-b4ce-11eb-9267-73d96230012e.png)

**Comment by KitOdin** [comment]
no

**Comment by PurpleButNotALight** [comment]
stop

**Comment by nickpythonluajava** [comment]
"ninjamuffin99 closed"

**Comment by B-Si** [comment]
What why?

**Comment by KitOdin** [comment]
Because this is unrelated, its just the b-sides icon grid, no real issue, and kinda pointless.
