### ISSUE TITLE
Question:  when i get the source code it wont llet me play the gameeeee

### ISSUE THREAD

**Issue by B13D4R** [ninjamuffin99/Funkin#1095]

**Comment by Steviegt6** [comment]
The `README` has instructions for compilation. Play it on Newgrounds or Itch.io if you just want to play it, though.

**Comment by B13D4R** [comment]
yeah but im asking how do i get the source code and play the old version, here's an example: https://www.youtube.com/watch?v=IjHAk-xgeXA

**Comment by B13D4R** [comment]
oh and also how do i edit fla files

**Comment by B13D4R** [comment]
hello?

**Comment by PurpleButNotALight** [comment]
Okay so. If you want the version in that video download from this relase https://github.com/ninjamuffin99/Funkin/releases/tag/1.1.0 and for how to edit the fla files you have to use adove animate
