### ISSUE TITLE
Question: Who is GF?

### ISSUE THREAD

**Issue by B-Si** [ninjamuffin99/Funkin#1098]
This Question will show you who is GF?

**Comment by PurpleButNotALight** [comment]
why is this in the funkin issue tracker

**Comment by B-Si** [comment]
Question: Why PurpleButNotALight Does bring ninjamuffin99 (Blocker of issues)

**Comment by PurpleButNotALight** [comment]
> Question: Why PurpleButNotALight Does bring ninjamuffin99 (Blocker of issues)

![image](https://user-images.githubusercontent.com/75984453/118370433-f5076300-b5a7-11eb-9829-503f5e900785.png)

This issue dosen't even say anything about the game or GF. You are just filling the Funkin issue tracker with bloat.
