### ISSUE TITLE
Pico will win to reach IconGrid?

### ISSUE THREAD

**Issue by B-Si** [ninjamuffin99/Funkin#1099]
it isnt meant to be seen, its probably because boyfriend is too short probably ninjamuffin lazy

_Originally posted by @nickpythonluajava in https://github.com/ninjamuffin99/Funkin/issues/1072#issuecomment-838886906_

**Comment by nickpythonluajava** [comment]
now i'm confused

**Comment by B-Si** [comment]
But why?

**Comment by B-Si** [comment]
Hehe

**Comment by B-Si** [comment]
![Uploading Screenshot_20210514-145137_YouTube.jpg…]()

**Comment by B-Si** [comment]
![iconGrid](https://user-images.githubusercontent.com/84184839/118362528-84a51580-b598-11eb-9504-92e39df4c6c5.png)
![spiritFaceForward](https://user-images.githubusercontent.com/84184839/118362533-8b338d00-b598-11eb-85cf-4e0d8f559a04.png)
![bfPixelsDEAD](https://user-images.githubusercontent.com/84184839/118362536-8bcc2380-b598-11eb-877f-c48d26e4887b.png)
![senpai](https://user-images.githubusercontent.com/84184839/118362539-8d95e700-b598-11eb-97d1-8cc22acc449b.png)
![senpaiPortrait](https://user-images.githubusercontent.com/84184839/118362540-8ec71400-b598-11eb-96c2-edcbf2c29405.png)
![Uploading 20210413_123124.png…]()

**Comment by B-Si** [comment]
![senpaiCrazy](https://user-images.githubusercontent.com/84184839/118362546-94bcf500-b598-11eb-90dc-7850cab27cc7.png)
![bfPortrait](https://user-images.githubusercontent.com/84184839/118362547-9686b880-b598-11eb-95c4-b4e0e92b6ea4.png)
![bfPixel](https://user-images.githubusercontent.com/84184839/118362550-9981a900-b598-11eb-857e-47aca0900947.png)
![spiritFaceForward](https://user-images.githubusercontent.com/84184839/118362553-9ab2d600-b598-11eb-8044-0d7f2d447af3.png)
![bfPixelsDEAD](https://user-images.githubusercontent.com/84184839/118362554-9ab2d600-b598-11eb-8700-eb3e07c51cda.png)
![gfPixel](https://user-images.githubusercontent.com/84184839/118362557-9c7c9980-b598-11eb-8c9a-a5c0981d24bb.png)
![senpai](https://user-images.githubusercontent.com/84184839/118362559-9d153000-b598-11eb-9460-90c1a5ffdab7.png)
![senpaiPortrait](https://user-images.githubusercontent.com/84184839/118362561-9dadc680-b598-11eb-8b8a-5e593bad636c.png)
![spirit](https://user-images.githubusercontent.com/84184839/118362563-9e465d00-b598-11eb-94f7-07a8fc32c35e.png)
![senpaiCrazy](https://user-images.githubusercontent.com/84184839/118362566-9f778a00-b598-11eb-80a1-7b15d2bb6755.png)
![bfPortrait](https://user-images.githubusercontent.com/84184839/118362568-a0102080-b598-11eb-82ed-602b696c8326.png)
![20210413_123241](https://user-images.githubusercontent.com/84184839/118362569-a0a8b700-b598-11eb-9bff-a1aef495db58.png)
![bfPixel](https://user-images.githubusercontent.com/84184839/118362570-a1414d80-b598-11eb-94b7-b0e21e2547df.png)
![Uploading iconGrid (1).png…]()

**Comment by nickpythonluajava** [comment]
**W H A T**

**Comment by B-Si** [comment]
![Uploading evilBG.png…]()

**Comment by B-Si** [comment]
![Uploading upperBop.png…]()

**Comment by B-Si** [comment]
![bgEscalator](https://user-images.githubusercontent.com/84184839/118362656-0e54e300-b599-11eb-97f9-f4ad37ab7831.png)

**Comment by B-Si** [comment]
![Screenshot_20210514-145137_YouTube](https://user-images.githubusercontent.com/84184839/118362700-40fedb80-b599-11eb-95d4-ec11babc03e9.jpg)
![Uploading Screenshot_20210514-145137_YouTube.jpg…]()

**Comment by B-Si** [comment]
![Screenshot_20210515-162205](https://user-images.githubusercontent.com/84184839/118362796-c71b2200-b599-11eb-9257-62bf3cd6c7ac.jpg)
Girlfriend is not singing a arrow

**Comment by B-Si** [comment]
Full details here

**Comment by B-Si** [comment]
![Screenshot_20210515-162445](https://user-images.githubusercontent.com/84184839/118362846-17927f80-b59a-11eb-8d50-bc5f85863b1b.jpg)

**Comment by B-Si** [comment]
![Screenshot_20210515-162627](https://user-images.githubusercontent.com/84184839/118362882-5294b300-b59a-11eb-9dcc-76002233143b.jpg)
![Screenshot_20210515-162621](https://user-images.githubusercontent.com/84184839/118362885-56283a00-b59a-11eb-9f4a-d19e997147d1.jpg)

**Comment by B-Si** [comment]
Take a look of there
Senpai Sing Randoms
![Screenshot_20210515-163135](https://user-images.githubusercontent.com/84184839/118363028-20d01c00-b59b-11eb-9cc7-13b433f77dc4.jpg)

**Comment by AMTitan** [comment]
why is this an issue? your just wasting time and idk if you know that and you have made like 5 issues that don't mean anything just stop.

**Comment by PurpleButNotALight** [comment]
I'm done. Please shut the fuck up. You are literally making anything actually related to any issues to the game.

**Comment by Windows1Door2Daniel** [comment]
As i said before

Explain to the mod creator

not to the vanilla game creator

**Comment by Windows1Door2Daniel** [comment]
> I'm done. Please shut the fuck up. You are literally making nothing actually related to any issues to the game.

Whoa pal

dont swear

i sweared before and i got flagged and i deleted my account and created this account
