### ISSUE TITLE
Bug Report: i found a new bug how do i fix this

### ISSUE THREAD

**Issue by sebby09559** [ninjamuffin99/Funkin#1110]
how do i fix this i need help  with this can anyone help me with it???
![image](https://user-images.githubusercontent.com/42832765/118394865-dc677d80-b679-11eb-8a6a-54a244cd6965.png)

**Comment by Rs232k** [comment]
Not a bug, install all needed.

**Comment by VMGuy23** [comment]
2017 VsDevCmd missing happens _with_ the needed stuff

**Comment by bruhboy345** [comment]
please read README.md

**Comment by ACrazyTown** [comment]
This is not a bug, you didn't install the stuff required for building on Windows. Read the README carefully.

**Comment by VMGuy23** [comment]
I've installed EVERYTHING AND MORE and it needs 2017 VsDevCmd. NOT A MISTAKE BY THE USER

**Comment by ACrazyTown** [comment]
Try running `lime build windows -debug` in the project's directory instead of running the build script? Does that change anything?

**Comment by VMGuy23** [comment]
That's what i'm doing :)

**Comment by sebby09559** [comment]
> I've installed EVERYTHING AND MORE and it needs 2017 VsDevCmd. NOT A MISTAKE BY THE USER

how do i fix this

**Comment by sebby09559** [comment]
> Try running `lime build windows -debug` in the project's directory instead of running the build script. Does that change anything?

this error now dose this to all of my fnf mod im making for just getinng a release .exe file

**Comment by sebby09559** [comment]
hey how do get it then

**Comment by ACrazyTown** [comment]
> > Try running `lime build windows -debug` in the project's directory instead of running the build script. Does that change anything?
> 
> this error now dose this to all of my fnf mod im making for just getinng a release .exe file

What? I don't really get what you're saying, could you clarify?

**Comment by sebby09559** [comment]
like i get this error all the time when i try to complie it i can't fix this how do i get 2017 devcmdfile how do i get it??

**Comment by ACrazyTown** [comment]
> like i get this error all the time when i try to complie it i can't fix this how do i get 2017 devcmdfile how do i get it??

What version of Visual Studio Community did you install?

**Comment by VMGuy23** [comment]
I have 2019 and have same issue. 2019 is the only downloadable now.

**Comment by Rs232k** [comment]
Why you installed 2019? Install what it said.

**Comment by Rs232k** [comment]
Why you installed 2019? Install what it said.

**Comment by VMGuy23** [comment]
2019, needed AND MORE
stll not working

**Comment by Rs232k** [comment]
Idk, in last month it worked, didn't tried new versions. But i don't think something changed in install components.

**Comment by sebby09559** [comment]
> > like i get this error all the time when i try to complie it i can't fix this how do i get 2017 devcmdfile how do i get it??
> 
> What version of Visual Studio Community did you install?

i have both 2019 version of vs and 2017 of vs

**Comment by sebby09559** [comment]
vs is virtural studio

**Comment by sebby09559** [comment]
i think i fixed it or not

**Comment by sebby09559** [comment]
nope it still don't work

**Comment by VMGuy23** [comment]
I just have 2019
does not work

**Comment by wellsilver** [comment]
Follow instructions in readme.md and download 20 gigabytes of stuff

**Comment by VMGuy23** [comment]
yep, ive done that

did it first

**Comment by ItzRiotz** [comment]
have you installed Visual Studio Build Tools 2017

**Comment by VMGuy23** [comment]
Where do I get that

**Comment by sebby09559** [comment]
can you give me a link to that??

> have you installed Visual Studio Build Tools 2017

**Comment by sebby09559** [comment]
> > like i get this error all the time when i try to complie it i can't fix this how do i get 2017 devcmdfile how do i get it??
> 
> What version of Visual Studio Community did you install?

i have both 2017 and 2019 of vs

**Comment by VMGuy23** [comment]
> can you give me a link to that??
> 
> > have you installed Visual Studio Build Tools 2017

I used DevOps account to download not sure if its legal to send a link to the exe

**Comment by ItzRiotz** [comment]
> 
> 
> can you give me a link to that??
> 
> > have you installed Visual Studio Build Tools 2017

It is in the installer, but I see you closed the issue so I guess it's fixed?
