### ISSUE TITLE
2 Suggestions

### ISSUE THREAD

**Issue by aflacc** [ninjamuffin99/Funkin#1118]
I have two ideas that could really help the game. One of them helps a recent event that the community is upset about and the other would just make you rich ninja. Now I know your paying attention cuz I mentioned money. So let me just explain my ideas.

### 1) Patreon
I think you should set up a patreon for Friday Night Funkin' along with the Kickstarter. I'd try my best to support you guys if you set one up and I think you could even have it so the Patreon had special rewards for certain tiers.

### 2) License
Yeah I know you changed it, and thats why I'm making this suggestion. I'm pretty sure I remember seeing a license that would fit for what your requesting of us. Now I'm not fully sure how licenses work or how to read them but I found [this](https://choosealicense.com/licenses/) website for picking a license. If anyone wants to help me figure out which one will fit this please let me know here.

**Comment by ninjamuffin99** [comment]
we dont need patreon lol

**Comment by aflacc** [comment]
ok well im glad you took time to read it keep up the good work
