### ISSUE TITLE
(IF I WANT TO NOT SEE THEPLANK 

### ISSUE THREAD

**Issue by B-Si** [ninjamuffin99/Funkin#1221]

**Comment by ACrazyTown** [comment]
What

**Comment by NotHyper-474** [comment]
What?

**Comment by nickpythonluajava** [comment]
Understandable, have a nice day

**Comment by jbmagination** [comment]
bring the plank to me

**Comment by prokube** [comment]
storke

**Comment by time-guy890** [comment]
WHAT? NANI?

**Comment by ThePlank** [comment]
lol what. why did you make a issue about me?

**Comment by jbmagination** [comment]
if you want to not see ThePlank

![image](https://user-images.githubusercontent.com/26027089/120794951-db05d400-c506-11eb-97ab-9bf8b13f9330.png)

**Comment by ThePlank** [comment]
> if you want to not see ThePlank
> 
> ![image](https://user-images.githubusercontent.com/26027089/120794951-db05d400-c506-11eb-97ab-9bf8b13f9330.png)

he makes unrelated issues mostly about the b-side icongrid and blames me for bringing minjamuffin99 to the issue

**Comment by VMGuy23** [comment]
Hi - I think that someone should report B-Si. They are adding unnecessary issues and not making much sense.

**Comment by jbmagination** [comment]
@ThePlank yes, I'm aware! but if they don't wanna see you they can literally just block you problem solved

**Comment by ThePlank** [comment]
ninjamuffin pls close

**Comment by FNFPlayer101** [comment]
B-Si can you stop making these it's annoying :/

**Comment by FNFPlayer101** [comment]
> 
> 
> Hi - I think that someone should report B-Si. They are adding unnecessary issues and not making much sense.
done.

**Comment by VMGuy23** [comment]
nice

**Comment by bonkmaykrQ** [comment]
I'm pretty sure OP can get their Github account sussed for posting spam like this... 

Ninjamuffin can also ban them from the repo lul

**Comment by ACardboardBox1** [comment]
> 
> 
> I'm pretty sure OP can get their Github account sussed for posting spam like this...
> 
> Ninjamuffin can also ban them from the repo lul

SUS :octocat: lol anyways, yeah i reported their account for spam, haven't got an update

**Comment by nickpythonluajava** [comment]
> lol what. why did you make a issue about me?

he probably just hates you
