### ISSUE TITLE
Question: How can I use older versions of Friday Night Funkin' (2.6.8 - 2.7.0) to using newer versions? (2.7.1)

### ISSUE THREAD

**Issue by WeirdoUwU** [ninjamuffin99/Funkin#1235]
I've been trying to get a chart of mine onto a newer version of Friday Night Funkin', the old chart was made in 2.6.8, and I'm tryin' to transfer it to 2.7.1, though it keeps sayin' the chart is invalid or some shit. And when it loads the notes float, and my custom character isn't there. Could you help me with this?

**Comment by VMGuy23** [comment]
Hi - Could you show me a screenshot of the exact error? Thanks.

**Comment by WeirdoUwU** [comment]
This issue came up a while ago, I don't have the chart anymore. But I can tell more details, would you like me to?

**Comment by VMGuy23** [comment]
Yes please.

**Comment by WeirdoUwU** [comment]
I was trying to get my chart into a newer version (Of course), so I moved the .json into a new folder called "new", I named the .json "new-hard.json" and added "new" to freeplaySonglist. When I loaded the song it didn't have my monkey (Note: my character was a monkey), instead it had dad. The background was also the tutorial background, which was originally supposed to be the Pico background. And one more thing, my custom arrow skin didn't show, they were supposed to be different colors. (Note: the arrows were in a seperate png/xml file.) And once the first few arrows came, they started jittering. I could do everything fine, just my opponent wouldn't do anything because the arrows never actually got to where they were supposed to be hit.

**Comment by WeirdoUwU** [comment]
Oh and yes, I had a song for it.
Also called new-Inst and new-Voices

**Comment by VMGuy23** [comment]
Was there new.json and new-easy.json?

**Comment by WeirdoUwU** [comment]
No, do you think this would be the problem?
I was using modding+ just the other day and I didn't add an "-easy" 'nor did I add just the name.

**Comment by VMGuy23** [comment]
It might have been a problem. Maybe the unmodified game requires easy difficulties. I expect it to require a normal though (no ending, new.json)

**Comment by WeirdoUwU** [comment]
Okay, I will now close this. Thank you for your help!
