### ISSUE TITLE
in kade on your engine have a line on it

### ISSUE THREAD

**Issue by joshuaword2alt** [ninjamuffin99/Funkin#1294]
pls fix your line pls on the arrows

**Comment by ThePlank** [comment]
https://github.com/KadeDev/Kade-Engine

**Comment by MenonPenguin89420** [comment]
As ThePlank said, please move this issue to the KadeEngine github page and not the original page.

**Comment by objectionist** [comment]
ayo this is the official github not kade's

**Comment by ThePlank** [comment]
> pls fix your line pls on the arrows

Oh, right you are talkin about the Down arrow not being properly generated?
This is fixed in 0.2.8.0, so when that releases KadeDev will merge the week 7 source code with the engine and it will be probally fixed.

**Comment by joshuaword2alt** [comment]
on tiktok when i-win was posted on youtube and tiktok ninjamufffin99 said it was fix in the new week 7 update
