### ISSUE TITLE
Ninjamuffin... it is time

### ISSUE THREAD

**Issue by VMGuy23** [ninjamuffin99/Funkin#1305]
@ninjamuffin99, it has reached the time where you make Week 7 public. You said it will release when Newgrounds result is first or second. It now is. Now go, and make it public!

![image](https://user-images.githubusercontent.com/81651922/123168732-47258900-d470-11eb-85d6-8fe96358c23f.png)

**Comment by ninjamuffin99** [comment]
not 1st result tho, srry

**Comment by VMGuy23** [comment]
you said first or second

**Comment by nickpythonluajava** [comment]
- # **_poggrs_**

**Comment by KitOdin** [comment]
come on everyone lets push it to the number 1 search result!

**Comment by VMGuy23** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOO

THE DUMB COMMUNITY PREFERS THE WIIPEDIA OVER THE ACTUAL NG GAME AND WIKI HAS TAKEN OVER

**Comment by Sincere1224** [comment]
- [ ]

**Comment by VMGuy23** [comment]
?

**Comment by nickpythonluajava** [comment]
> @NOOOOOOOOOOOOOOOOOOOOOOOOOOO
> 
> 
> 
> THE DUMB COMMUNITY PREFERS THE WIIPEDIA OVER THE ACTUAL NG GAME AND WIKI HAS TAKEN OVER

![rip](https://i.kym-cdn.com/photos/images/original/001/813/719/6bf.gif)

**Comment by ThePlank** [comment]
for some reason in poland google has the 6th result on google because of how many pepole dont know that the itch exists and just play reuploads on sites
