### ISSUE TITLE
Poggers

### ISSUE THREAD

**Issue by Windows1Door2Daniel** [ninjamuffin99/Funkin#1307]
https://youtu.be/zjnJk5V9nSM

Enchance the practice mode by 

Letting you to place checkpoints to go back to a specific point

View how many health you lost in a turn

View the timing you pressed a arrow (like Very late, Late, Soon, Very soon, Perfect)

**Comment by nickpythonluajava** [comment]
> https://youtu.be/zjnJk5V9nSM
> 
> 
> 
> Enchance the practice mode by 
> 
> 
> 
> Letting you to place checkpoints to go back to a specific point
> 
> 
> 
> View how many health you lost in a turn
> 
> 
> 
> View the timing you pressed a arrow (like Very late, Late, Soon, Very soon, Perfect)
> 
> 
> 
> 
> 
> 

okay but what is the link

**Comment by Windows1Door2Daniel** [comment]
> > https://youtu.be/zjnJk5V9nSM
> > Enchance the practice mode by
> > Letting you to place checkpoints to go back to a specific point
> > View how many health you lost in a turn
> > View the timing you pressed a arrow (like Very late, Late, Soon, Very soon, Perfect)
> 
> okay but what is the link

Totally a Rickroll

**Comment by Windows1Door2Daniel** [comment]
With
1 broken drill
2 years in jail
3 tires shot
4 panicked robers
5 bullets left
6 Dozers charging
7 Tazers buzing
8 SWATs rapeling
9 hostages fleeing
10 seconds respond time
11 doors to lockpick
12 bags of coke

And a broken piece sh*t drill

**Comment by 4techguns** [comment]
what does payday 2 have to do with fnf?

please close. this issue isnt needed

**Comment by Windows1Door2Daniel** [comment]
> what does payday 2 have to do with fnf?
> 
> please close. this issue isnt needed

Both are games
The games have good music especially Payday 2

**Comment by siky112** [comment]
> With
> 1 broken drill
> 2 years in jail
> 3 tires shot
> 4 panicked robers
> 5 bullets left
> 6 Dozers charging
> 7 Tazers buzing
> 8 SWATs rapeling
> 9 hostages fleeing
> 10 seconds respond time
> 11 doors to lockpick
> 12 bags of coke
> 
> And a broken piece sh*t drill

and a partridge in a pear treeeeeeeee
