### ISSUE TITLE
how do i change the art  for my art????

### ISSUE THREAD

**Issue by time-guy890** [ninjamuffin99/Funkin#1323]
## What is your question?
How do I Change the art for my mod????

**Comment by theblobscp** [comment]
I'm pretty sure you can just replace the files.

**Comment by time-guy890** [comment]
DUDE IM ON CHROME OS YOU THINK I CAN DO THAT?

**Comment by VMGuy23** [comment]
IMage editor

**Comment by VMGuy23** [comment]
*Image

**Comment by nickpythonluajava** [comment]
> DUDE IM ON CHROME OS YOU THINK I CAN DO THAT?

just download linux version

**Comment by theblobscp** [comment]
> DUDE IM ON CHROME OS YOU THINK I CAN DO THAT?

I'm on chrome os rn and I could probably do it. What's your excuse?

**Comment by boston2029** [comment]
Brother you can download FNF on Chromebook and replace the files but you can't launch the game

**Comment by boston2029** [comment]
Just get VSCode linux version and build the source if you want the HTML version (web version)

**Comment by theblobscp** [comment]
> Just get VSCode linux version and build the source if you want the HTML version (web version)
<li><a href="https://support.google.com/chromebook/answer/9145439?hl=en">Google Article</a></li>
<li><a href= "https://code.visualstudio.com/blogs/2020/12/03/chromebook-get-started">VSCode Article</a></li>

**Comment by HmAhYesTheFloorHereIsMadeOutOfFloor** [comment]
> DUDE IM ON CHROME OS YOU THINK I CAN DO THAT?

yes. yes you can.

**Comment by theblobscp** [comment]
Seriously, some people are so lazy. Just spend 10 minutes on google, and be done.

**Comment by ninjamuffin99** [comment]
chrome os isnt supported

**Comment by AbnormalPoof** [comment]
actually, it is supported kinda
you can build the html5 version and itd work just fine

**Comment by theblobscp** [comment]
You could also try Chrome os dev mode, which gives you access to the Linux version

**Comment by AbnormalPoof** [comment]
> You could also try Chrome os dev mode, which gives you access to the Linux version

you can also install linux via settings and have a working debian container, then build the html5 version and you have a (mostly) lagless version of fnf

**Comment by theblobscp** [comment]
That's what I said...

**Comment by AbnormalPoof** [comment]
not really
you said to enable developer mode, which invokes a full system wipe along with giving you access to system files. its an extremely dangerous action
