### ISSUE TITLE
Bug Report: 

### ISSUE THREAD

**Issue by idragons962** [ninjamuffin99/Funkin#1325]
When I Try Loading It Is Says This
error:couldent find flixel-ul
 
Can You Tell Me Why?

**Comment by VMGuy23** [comment]
ITS NOT A BUG
```
haxelib install flixel-ui
```

**Comment by ACardboardBox1** [comment]
> 
> 
> ITS NOT A BUG
> 
> ```
> haxelib install flixel-ui
> ```

this is pain

**Comment by nickpythonluajava** [comment]
> ITS NOT A BUG
> 
> ```
> 
> haxelib install flixel-ui
> 
> ```

`haxelib run setup flixel-ui`

**Comment by VMGuy23** [comment]
> > ITS NOT A BUG
> > ```
> > 
> > haxelib install flixel-ui
> > ```
> 
> `haxelib run setup flixel-ui`

i havent done this, mine works
