### ISSUE TITLE
Question: While trying to add dialogue to a little Kade Engine mod I am doing for myself, I decided to not add dialogue, and now this error pops up.

### ISSUE THREAD

**Issue by TheGamingCat89** [ninjamuffin99/Funkin#1367]
I've deleted the dialogue code and the .txt files for the dialogue, any idea on what's causing this issue?
![image](https://user-images.githubusercontent.com/81439207/125548162-1ca057ea-1829-45a4-b0bc-4453acb40346.png)

**Comment by LiterallyWize** [comment]
delete the text where you were adding dialogue in the source files
i've never added dialogue before but yeah you just have to delete that im pretty sure

**Comment by TheGamingCat89** [comment]
> delete the text where you were adding dialogue in the source files
> i've never added dialogue before but yeah you just have to delete that im pretty sure

yeah i said i deleted the .txt files and the code too, still pops up though

**Comment by TheKitBoi** [comment]
Put that message on Kade engine github
