### ISSUE TITLE
Bug Report: 0.2.8 on NG doesn't load

### ISSUE THREAD

**Issue by TheWaouh** [ninjamuffin99/Funkin#1385]
### If you are playing the game in a browser, what site are you playing it from?
[Newgrounds](https://www.newgrounds.com/portal/view/770371) or [Itch.io](https://ninja-muffin24.itch.io/funkin)? Specify below.
Newgrounds

### If you are playing the game in a browser, what browser are you using?
Chrome (or a Chromium based browser, i.e. Edge, Opera, etc.), Firefox, or Safari? Specify blow.
Chromium (edge)

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.
No downloaded version.

## What version of the game are you using? Look in the bottom left corner of the main menu.
0.2.8 (newgrounds limited timed)

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No.

## Please describe your issue. Provide extensive detail and images if possible.
When attempting to run the Newgrounds version, it freezes during loading, and the console tells me that it cannot find the cutscenes and Kickstarter trailer MP4 files.
I have tried clearing cache, cookies, and another browser.

**Comment by ThePlank** [comment]
try to reload a couple of times

**Comment by TheWaouh** [comment]
> try to reload a couple of times

I have tried, it doesn't work, always gets stuck at 77-81%.

**Comment by hdboye** [comment]
you don't have  enough ram to load it in

**Comment by TheWaouh** [comment]
> you don't have enough ram to load it in

It worked once. And as I said, it is saying it can't find the cutscenes and Kickstarter trailer MP4 files from a "upload.newgrounds.com" URL. It is not my ram.
