### ISSUE TITLE
Bug Report: Bouncing loading screen

### ISSUE THREAD

**Issue by WinnerWinds** [ninjamuffin99/Funkin#1389]
This was noticed in the NEWGROUNDS preview of 0.2.8

When the game enters loading a new level, clicking enter makes the charecters shown to bounce. This is a minor bug and does not affect the game

**Comment by CyndaquilDAC** [comment]
This is quite literally a feature lmao

**Comment by SmashingGoomba** [comment]
Isnt this literally intended???

**Comment by Windows1Door2Daniel** [comment]
If would be a bug then the characters wouldnt bounce

**Comment by WinnerWinds** [comment]
Actually the WHOLE IMAGE bounces not just the charecters. the loading grafiti and the drawn charecters all bounce at once

**Comment by Windows1Door2Daniel** [comment]
> Actually the WHOLE IMAGE bounces not just the charecters. the loading grafiti and the drawn charecters all bounce at once

Yeah, the image and the characters are in a single sprite

**Comment by josetzunun** [comment]
> Actually the WHOLE IMAGE bounces not just the charecters. the loading grafiti and the drawn charecters all bounce at once

HAHAH LOLOLOL

**Comment by ThePlank** [comment]
he's talking about it sizing from the top left and not the middle.

**Comment by Windows1Door2Daniel** [comment]
This shet took a lot and didnt even finished

downloaded this shet since 11 am now its 2 am

![SharedScreenshot](https://user-images.githubusercontent.com/81389527/129704176-12396a09-ea53-44b4-8521-ea6b67b2c8e8.jpg)

**Comment by siky112** [comment]
that's intentional

**Comment by WinnerWinds** [comment]
its unnatural and bounces from the top left. If it bounced from the center i wouldnt say a word

**Comment by ninjamuffin99** [comment]
intended
