### ISSUE TITLE
Bug Report: Charting

### ISSUE THREAD

**Issue by HmAhYesTheFloorHereIsMadeOutOfFloor** [ninjamuffin99/Funkin#1398]
So I added my custom song in the freeplay, songs, and preload, but when I try to play it the arrows start to go, but when the opposite side hits a note, it just bugs and the arrows don't move

https://user-images.githubusercontent.com/63616870/127072617-447a9742-5e60-4f0a-8a33-45f40070c743.mp4

**Comment by CarGithubus** [comment]
This happened to me when I just changed the file extension .mp3 to .ogg. Try using a converter.

**Comment by ThePlank** [comment]
I think this happens when the song loads but it isnt in the right format, make sure to convert your mp3 file to ogg with something like audacity if you made the song in mp3

**Comment by nickpythonluajava** [comment]
this happened when i put the audios in the wrong folder

**Comment by HmAhYesTheFloorHereIsMadeOutOfFloor** [comment]
> I think this happens when the song loads but it isnt in the right format, make sure to convert your mp3 file to ogg with something like audacity if you made the song in mp3

aight thanks :>

**Comment by HmAhYesTheFloorHereIsMadeOutOfFloor** [comment]
> This happened to me when I just changed the file extension .mp3 to .ogg.

thanks :>

**Comment by HmAhYesTheFloorHereIsMadeOutOfFloor** [comment]
> This happened to me when I just changed the file extension .mp3 to .ogg.

alright, ill try that

**Comment by HmAhYesTheFloorHereIsMadeOutOfFloor** [comment]
> this happened when i put the audios in the wrong folder

alright, ill see if thats the issue
