### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by Snow8347** [ninjamuffin99/Funkin#1407]
I tried installing polymod and it said
haxelib git polymod https://github.com/larsiusprime/polymod
.git
You already have polymod version git installed.
Updating polymod version git ...
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
i am trying to install it for kade engine 1.6

**Comment by TheHENOOB** [comment]
If you are questioning about kade engine you should make this issue on the kade engine repository
