### ISSUE TITLE
making a reset button

### ISSUE THREAD

**Issue by MrClogsworthYT** [ninjamuffin99/Funkin#1445]
im making a reset button lol

(will open a pull request)

**Comment by ThePlank** [comment]
There is already a reset button (R) or you can just ghost tap till youre dead

**Comment by MrClogsworthYT** [comment]
i meant data reset

**Comment by ACrazyTown** [comment]
Pretty sure ninjamuffin's gonna add it, as mentioned in #1403

**Comment by MrClogsworthYT** [comment]
ik but i wanna see if i can code that

**Comment by Johnny-hardcodeti** [comment]
welp you could just reinstall it

**Comment by ThePlank** [comment]
> welp you could just reinstall it

"reinstall"

you can't actually "install" the game.

**Comment by ninjamuffin99** [comment]
yeah gon make reset button in a redone options eventually lol!

**Comment by MrClogsworthYT** [comment]
oh hi

**Comment by MrClogsworthYT** [comment]
oh hi
