### ISSUE TITLE
my age is 10

### ISSUE THREAD

**Issue by YousefTamer67** [ninjamuffin99/Funkin#1447]
my age is 10

**Comment by MrClogsworthYT** [comment]
,,,

**Comment by siky112** [comment]
cool

**Comment by Windows1Door2Daniel** [comment]
Ok

**Comment by YousefTamer67** [comment]
i can't chat in the discord server

**Comment by ThePlank** [comment]
ok boomer

**Comment by napstaa967** [comment]
> i can't chat in the discord server

and neither can you in github
![image](https://user-images.githubusercontent.com/57607350/130142562-d9701034-bdd5-4b4c-942e-db21aa343e9f.png)

**Comment by ninjamuffin99** [comment]
w
