### ISSUE TITLE
 Exporting the game windows

### ISSUE THREAD

**Issue by Rysik5318** [ninjamuffin99/Funkin#1448]
I want to compile an empty fnf, but I have all the files created except the .exe file
![2021-08-19_20-02-28](https://user-images.githubusercontent.com/72207886/130103745-39297a6d-b141-412a-9273-8adcf6896983.png)

After compilation, it just spam something, but the exe file does not appear. I installed everything that is needed for compilation, I don't even know what the problem is. Or is it the way it should be?
![2021-08-19_19-23-28](https://user-images.githubusercontent.com/72207886/130103973-9332f03e-b43d-4e10-8cfc-e53d1b29c7c2.png)

still writes a few errors
![2021-08-19_20-03-32](https://user-images.githubusercontent.com/72207886/130104379-b0592b33-d545-4506-b242-e5679549a77f.png)

**Comment by napstaa967** [comment]
its normal, let it go

what's happening:
haxe uses cplusplus to build to windows, aka it converts from hx to cpp
then it uses a microsoft compiler to convert all the cpp files into a binary (exe)
what the console is doing is showing you what file is being compiled at the moment, including the haxe toolkit

this happens every time you build the game on a new download

this process may take from 30 mins to over 2 hours depending on how fast your pc is

**Comment by Rysik5318** [comment]
> это нормально, отпусти
> 
> что происходит:
> haxe использует cplusplus для сборки в окнах, иначе говоря, он конвертирует из hx в cpp,
> затем он использует компилятор microsoft для преобразования всех файлов cpp в двоичный (exe)
> то, что делает консоль, показывает вам, какой файл компилируется в момент, включая инструментарий haxe
> 
> это происходит каждый раз, когда вы создаете игру для новой загрузки
> 
> этот процесс может занять от 30 минут до 2 часов в зависимости от скорости вашего компьютера.

Thx
