### ISSUE TITLE
Week7 source code when

### ISSUE THREAD

**Issue by DzGithub2805** [ninjamuffin99/Funkin#1468]
:trollface:

**Comment by Windows1Door2Daniel** [comment]
IDK

**Comment by napstaa967** [comment]
i don't know but ninjamuffin has been active recently so its prob really soon

**Comment by MrClogsworthYT** [comment]
**he said when fnf newgrounds link is the first one when you search fnf he will release it**

**Comment by Cheemsandfriends** [comment]
@MrClogsworthYT 
![imagen](https://user-images.githubusercontent.com/84867412/130508768-6b30f418-137e-4e48-a8f8-8bce59cca237.png)
