### ISSUE TITLE
CAPTCHA issue

### ISSUE THREAD

**Issue by Zephyy-Chan** [ninjamuffin99/Funkin#217]
I'm not sure if this is a problem with my computer, but the CAPTCHA for creating an account on NewGrounds simply doesn't exist so I can't make an account. I've disabled my ad blocker and tried it. i tried clearing my cached data. 
I just want to save medals :((
![image](https://user-images.githubusercontent.com/77704324/105108108-a1539580-5a5d-11eb-80ae-5562eac4cc7e.png)

**Comment by ninjamuffin99** [comment]
oops, this would prob be an issue with Newgrounds, not Friday Night Funkin'
Feel free to email them at support@newgrounds.com !
