### ISSUE TITLE
Antialising not taken into account when making the atlases sheets

### ISSUE THREAD

**Issue by xChillax** [ninjamuffin99/Funkin#22]
So, I was just playing it and me being so picky noticed something.

![Screenshot_1](https://user-images.githubusercontent.com/6830124/100932532-c51d4500-34ca-11eb-997e-1656a8934c68.png)

Do you see it?

![image](https://user-images.githubusercontent.com/6830124/100932566-d1a19d80-34ca-11eb-9a6d-211c5384e62d.png)
![image](https://user-images.githubusercontent.com/6830124/100935616-17606500-34cf-11eb-9350-c8cd28b9d242.png)

Yes, I saw like 1 pixel off on the arrow.
I thought it was the .xml file but nope, the coordinates for them are precise and the same size as the real arrow notes.

**Why does this happen? you might ask.**
You see when using antialising (pixel smoothing) it smooths out the edges of it. Which means.... the edges of the sprites pixels will go off their boundaries if the boundaries are set TOO close to the last pixel they had.

So this:
![image](https://user-images.githubusercontent.com/6830124/101055033-4e368980-3568-11eb-9fab-3405c4062783.png)

Turns into this:
![image](https://user-images.githubusercontent.com/6830124/101055384-9bb2f680-3568-11eb-9075-29aaf9341626.png)
(Small visual representation, ingame its technically a lot smoother but you get the idea)

The fix for this issue would be editing all the atlases that have no space whatsoever on its sides, and make them have atleast 1 or 4 pixels of emptyness (to accomodate with antialising).

**Comment by ninjamuffin99** [comment]
easy fix just gotta rexport the spritesheets, which i will do eventually because im lazy LOL

**Comment by ninjamuffin99** [comment]
i think someone fixed this for me in one of their PR's, closin!

**Comment by xChillax** [comment]
Oh, I just realized this was closed, and I went to check if it was fixed.

![image](https://user-images.githubusercontent.com/6830124/103915860-83477600-50ea-11eb-839a-514cb9d2acd5.png)

And nope, still there.

Also, since this applies to other assets too, not only arrows, this happens aswell:
![image](https://user-images.githubusercontent.com/6830124/103916003-aeca6080-50ea-11eb-8592-ac035fca3b09.png)
