### ISSUE TITLE
Week 2: Monster Missing BF's Vocals

### ISSUE THREAD

**Issue by EmoLeaf** [ninjamuffin99/Funkin#838]
I was playing Friday Night Funkin' on Newgrounds so I could check out the Week 7 update. I decided to also play Week 2's last song, Monster, on Normal mode from Freeplay and found that about a third of the way through the song, the vocals for Boyfriend just disappeared. I have tried this track a couple times and the vocals for BF seem to disappear only sometimes and in random places of the song. For comparison, I also played Pico's and Tankman's songs; BF's vocals worked just fine there. I wasn't able to capture before the vocals dropped, but I do have a video of it not working afterwards. I hope it can be of some help.

https://user-images.githubusercontent.com/72285363/115608781-921df700-a29b-11eb-9293-374548f1ccb3.mov

**Comment by ninjamuffin99** [comment]
fixed in week 7 stuf
